import nlpaug.augmenter.char as nac
import nlpaug.augmenter.word as naw
import random

class StressTestGenerator:

  # initilize the augmenters for each type of stress test
  def __init__(self):
    # case augmentation
    self.char_augmenter = nac.RandomCharAug(action="substitute", verbose=0)
    # word augmentation
    self.word_augmenter = naw.RandomWordAug(action="swap", verbose=0)

    # typo augmentation
    self.typo_aug = nac.KeyboardAug(aug_char_p=0.1, aug_word_p=0.1, verbose=0)

    # homoglyphs augmentation
    self.homoglyphs = {'a': 'а', 'e': 'е', 'o': 'о', 'p': 'р', 's': 'ѕ'}

  # inject leetspeak  into the text
  def inject_leetspeak(self, text):
    leets = {'e': '3', 'i': '1', 'a': '@', 's': '5', 'o': '0'}
    words = text.split()
    for i, word in enumerate(words):
      for char, leet in leets.items():
        if char in word:
          words[i] = word.replace(char, leet)
    return ' '.join(words)
  
  # inject homoglyphs into the text
  def inject_homoglyphs(self, text, intensity=0.1):
    chars = list(text)
    for i in range(len(chars)):
        if chars[i] in self.homoglyphs and random.random() < intensity:
            chars[i] = self.homoglyphs[chars[i]]
    return "".join(chars)

  # add an AI slop to the text
  def add_ai_slop(self, text):
    # generated by gemini
    slops = [
        "In conclusion, it is important to remember that ",
        "Furthermore, it should be noted that ",
        "To summarize the multifaceted nature of ",
        "I am thrilled and humbled to announce that ",
        "In today’s rapidly evolving digital landscape, ",
        "Let that sink in for a moment. ",
        "What most people fail to realize is that ",
        "This is a common misconception, and it's actually ",
        "The reality is much more nuanced than ",
        "The secret to unlocking your true potential lies in ",
        "It’s almost as if we are living in a society where ",
        "I’ve been doing a deep dive into the intersection of ",
        "Imagine a world where we didn't have to choose between ",
        "I didn't believe it at first, but then I realized that ",
        "The one simple trick that changed everything for me was ",
        "If you only read one thing today, make it this: ",
        "We need to have a serious conversation about the future of ",
        "To be fair, you have to realize that ",
        "This is a common misconception, and it's actually much more ",
        "While I see where you’re coming from, the reality is ",
        "It’s almost as if [sarcastic summary of the user's point]... ",
        "The sheer level of cognitive dissonance required to ",
        "This is the quintessential example of the Dunning-Kruger effect in ",
        "Can we talk about how problematic it is that ",
        "I’ve been doing a deep dive into this topic, and honestly, ",
        "I suspect I’ll be downvoted for this, but the truth is ",
        "Edit: Thanks for the gold! Just wanted to add that ",
        "It is crucial to consider the broader implications of ",
        "In the rapidly evolving landscape of ",
        "Ultimately, the key takeaway remains that ",
        "The answer is multifaceted and deeply nuanced, as ",
        "Moreover, one must take into account the fact that ",
        "In summary, the interplay between these various elements ",
        "As we delve deeper into the complexities of ",
        "It is essential to strike a balance between ",
        "This serves as a poignant testament to "
    ]
    return random.choice(slops) + text
  
  # generate a stress test for a single text
  def generate_stress_test(self, text: str) -> str:
    augmented_text = text
    # make everything random

    # randomly apply char augmentation
    if random.randint(0, 1):  # 1 = apply
      # print("applying char augmentation")
      augmented_text = self.char_augmenter.augment(augmented_text)
      if isinstance(augmented_text, list):
        augmented_text = augmented_text[0]

    # randomly apply word augmentation
    if random.randint(0, 1):
      # print("applying word augmentation")
      augmented_text = self.word_augmenter.augment(augmented_text)
      if isinstance(augmented_text, list):
        augmented_text = augmented_text[0]

    # randomly apply leetspeak
    if random.randint(0, 1):
      # print("applying leetspeak")
      augmented_text = self.inject_leetspeak(augmented_text)

    # randomly apply homoglyphs
    if random.randint(0, 1):
      # print("applying homoglyphs")
      augmented_text = self.inject_homoglyphs(augmented_text)

    # randomly add AI slop
    if random.randint(0, 1):
      # print("adding AI slop")
      augmented_text = self.add_ai_slop(augmented_text)

    # randomly apply typos
    if random.randint(0, 1):
      # print("applying typos")
      augmented_text = self.typo_aug.augment(augmented_text)
      if isinstance(augmented_text, list):
        augmented_text = augmented_text[0]

    return augmented_text

  # generate a stress-tested version of an entire HuggingFace Dataset
  def generate_stress_test_dataset(self, dataset, text_column: str = "text"):
    def _augment(example):
      example[text_column] = self.generate_stress_test(example[text_column])
      return example
    return dataset.map(_augment)

if __name__ == "__main__":
  tester = StressTestGenerator()
  print(tester.generate_stress_test("The quick brown fox jumps over the lazy dog."))